micronaut:
  application:
    name: mysqlMicronautRest
datasources:
  default:
    url: jdbc:mysql://localhost:3306/world
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Shiv
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
